name = "catTab"
prefix = "Ctab"
author = "Cat Harsis, Riouken & Gundy"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp",
    "*.paa",
    "settings/",
    "settings/ctab_settings.hpp",
    "custom_backgrounds/",
]
exclude = [
    "*.png",
    "*.pdn",
]

[version]
git_hash = 0 # Disabled
