/**** Device Settings ****/

#define QSETTINGS_COMMON QUOTE(COMMON)
#define QSETTINGS_MAIN QUOTE(Main)
#define QSETTINGS_TABLET QUOTE(Tablet)
#define QSETTINGS_ANDROID QUOTE(Android)
#define QSETTINGS_FBCB2 QUOTE(FBCB2)
#define QSETTINGS_TAD QUOTE(TAD)
#define QSETTINGS_MICRODAGR QUOTE(MicroDAGR)
#define QSETTINGS_UAVS QUOTE(uavDisplay)
#define QSETTINGS_HCAMS QUOTE(hcamDisplay)

#define SETTING_MODE_DESKTOP DESKTOP
#define QSETTING_MODE_DESKTOP QUOTE(SETTING_MODE_DESKTOP)
#define SETTING_MODE_BFT BFT
#define QSETTING_MODE_BFT QUOTE(SETTING_MODE_BFT)
#define SETTING_MODE_CAM_UAV UAV
#define QSETTING_MODE_CAM_UAV QUOTE(SETTING_MODE_CAM_UAV)
#define SETTING_MODE_CAM_HCAM HCAM
#define QSETTING_MODE_CAM_HCAM QUOTE(SETTING_MODE_CAM_HCAM)
#define SETTING_MODE_CAM_HCAM_FULL HCAM_FULL
#define QSETTING_MODE_CAM_HCAM_FULL QUOTE(SETTING_MODE_CAM_HCAM_FULL)
#define SETTING_MODE_CAM_UAVGUNNER_FULL UAVGUNNER_FULL
#define QSETTING_MODE_CAM_UAV_FULL QUOTE(SETTING_MODE_CAM_UAVGUNNER_FULL)
#define SETTING_MODE_MESSAGES MESSAGE
#define QSETTING_MODE_MESSAGES QUOTE(SETTING_MODE_MESSAGES)
#define SETTING_MODE_MESSAGES_COMPOSE COMPOSE
#define QSETTING_MODE_MESSAGES_COMPOSE QUOTE(SETTING_MODE_MESSAGES_COMPOSE)

#define SETTING_MODE mode
#define QSETTING_MODE QUOTE(SETTING_MODE)
#define QSETTING_MAP_SCALE_MIN QUOTE(mapScaleMin)
#define QSETTING_MAP_SCALE_MAX QUOTE(mapScaleMax)
#define QSETTING_POSITION_DIALOG QUOTE(dlgIfPosition)
#define QSETTING_POSITION_DISPLAY QUOTE(dspIfPosition)
#define QSETTING_SHOW_ICON_TEXT QUOTE(showIconText)
#define QSETTING_SHOW_MENU QUOTE(showMenu)
#define QSETTING_MAP_WORLD_POS QUOTE(mapWorldPos)
#define QSETTING_MAP_SCALE_DISPLAY QUOTE(mapScaleDsp)
#define QSETTING_MAP_SCALE_DIALOG QUOTE(mapScaleDlg)
#define QSETTING_MAP_TYPES QUOTE(mapTypes)
#define QSETTING_CURRENT_MAP_TYPE QUOTE(mapType)

#define SETTING_FEED_TYPE_UAV type_uav
#define QSETTING_FEED_TYPE_UAV QUOTE(SETTING_FEED_TYPE_UAV)
#define SETTING_FEED_TYPE_HCAM type_hcam
#define QSETTING_FEED_TYPE_HCAM QUOTE(SETTING_FEED_TYPE_HCAM)
#define QSETTING_FOLLOW_UAV QUOTE(followUAV)
#define QSETTING_FOLLOW_HCAM QUOTE(followHCam)
#define SETTING_CAM_UAV_CURRENT uavCam_curr
#define QSETTING_CAM_UAV_CURRENT QUOTE(SETTING_CAM_UAV_CURRENT)
#define SETTING_CAM_UAV_0 uavCam_0
#define QSETTING_CAM_UAV_0 QUOTE(SETTING_CAM_UAV_0)
#define SETTING_CAM_UAV_1 uavCam_1
#define QSETTING_CAM_UAV_1 QUOTE(SETTING_CAM_UAV_1)
#define SETTING_CAM_UAV_2 uavCam_2
#define QSETTING_CAM_UAV_2 QUOTE(SETTING_CAM_UAV_2)
#define SETTING_CAM_UAV_3 uavCam_3
#define QSETTING_CAM_UAV_3 QUOTE(SETTING_CAM_UAV_3)
#define SETTING_CAM_UAV_4 uavCam_4
#define QSETTING_CAM_UAV_4 QUOTE(SETTING_CAM_UAV_4)
#define SETTING_CAM_UAV_5 uavCam_5
#define QSETTING_CAM_UAV_5 QUOTE(SETTING_CAM_UAV_5)
#define SETTING_CAM_UAV_FULL uavCam_Full
#define QSETTING_CAM_UAV_FULL QUOTE(SETTING_CAM_UAV_FULL)

#define SETTING_CAM_HCAM_CURRENT helmetCam_curr
#define QSETTING_CAM_HCAM_CURRENT QUOTE(SETTING_CAM_HCAM_CURRENT)
#define SETTING_CAM_HCAM_0 helmetCam_0
#define QSETTING_CAM_HCAM_0 QUOTE(SETTING_CAM_HCAM_0)
#define SETTING_CAM_HCAM_1 helmetCam_1
#define QSETTING_CAM_HCAM_1 QUOTE(SETTING_CAM_HCAM_1)
#define SETTING_CAM_HCAM_2 helmetCam_2
#define QSETTING_CAM_HCAM_2 QUOTE(SETTING_CAM_HCAM_2)
#define SETTING_CAM_HCAM_3 helmetCam_3
#define QSETTING_CAM_HCAM_3 QUOTE(SETTING_CAM_HCAM_3)
#define SETTING_CAM_HCAM_4 helmetCam_4
#define QSETTING_CAM_HCAM_4 QUOTE(SETTING_CAM_HCAM_4)
#define SETTING_CAM_HCAM_5 helmetCam_5
#define QSETTING_CAM_HCAM_5 QUOTE(SETTING_CAM_HCAM_5)
#define SETTING_CAM_HCAM_FULL helmetCam_Full
#define QSETTING_CAM_HCAM_FULL QUOTE(SETTING_CAM_HCAM_FULL)

#define QSETTING_MAP_TOOLS QUOTE(mapTools)
#define QSETTING_HOOK_REFERENCE_MODE QUOTE(hookref)
#define QSETTING_NIGHT_MODE QUOTE(nightMode)
#define QSETTING_BRIGHTNESS QUOTE(brightness)
#define QSETTING_DEVICE_ENVIRONMENT QUOTE(environment)

#define QMAP_TYPE_SAT QUOTE(SAT)
#define QMAP_TYPE_TOPO QUOTE(TOPO)
#define QMAP_TYPE_BLACK QUOTE(BLK)

#define QDEVICE_AIR QUOTE(AIR)
#define QDEVICE_GROUND QUOTE(GROUND)

/**** UAV Cam Options ****/

#define CAM_UAV cam_uav
#define QCAM_UAV QUOTE(CAM_UAV)
#define CAM_HCAM cam_helmet
#define QCAM_HCAM QUOTE(CAM_HCAM)


/**** Draw Map Control Options ****/

#define DMC_SAVE_SCALE_POSITION     "SAVESCALEPOSITION"
#define DMC_RECENTER                "RECENTER"
#define DMC_DRAW_MARKERS            "DRAWMARKERS"
#define DMC_DRAW_HOOK               "DRAWHOOK"
#define DMC_VEHICLE_AVATAR          "DRAWVEHICLE"
#define DMC_HUMAN_AVATAR            "DRAWFEATHERLESSBIPED"
#define DMC_TAD_OVERLAY             "DRAWTADOVERLAY"
#define DMC_CONDITION               "DRAWINGCONDITION"

#define DMC_BFT_UAV QUOTE(UAVControls)
#define DMC_BFT_VEHICLES QUOTE(Vehicles)
#define DMC_BFT_GROUPS QUOTE(Groups)
#define DMC_BFT_MEMBERS QUOTE(Members)
