#define QSETTINGS_COMMON QUOTE(COMMON)
#define QSETTINGS_MAIN QUOTE(Main)
#define QSETTINGS_TABLET QUOTE(Tablet)
#define QSETTINGS_ANDROID QUOTE(Android)
#define QSETTINGS_FBCB2 QUOTE(FBCB2)
#define QSETTINGS_TAD QUOTE(TAD)
#define QSETTINGS_MICRODAGR QUOTE(MicroDAGR)

#define SETTING_MODE_DESKTOP DESKTOP
#define QSETTING_MODE_DESKTOP QUOTE(SETTING_MODE_DESKTOP)
#define SETTING_MODE_BFT BFT
#define QSETTING_MODE_BFT QUOTE(SETTING_MODE_BFT)
#define SETTING_MODE_CAM_UAV UAV
#define QSETTING_MODE_CAM_UAV QUOTE(SETTING_MODE_CAM_UAV)
#define SETTING_MODE_CAM_HELMET HCAM
#define QSETTING_MODE_CAM_HELMET QUOTE(SETTING_MODE_CAM_HELMET)
#define SETTING_MODE_CAM_HELMET_FULL HCAM_FULL
#define QSETTING_MODE_CAM_HELMET_FULL QUOTE(SETTING_MODE_CAM_HELMET_FULL)
#define SETTING_MODE_MESSAGES MESSAGE
#define QSETTING_MODE_MESSAGES QUOTE(SETTING_MODE_MESSAGES)
#define SETTING_MODE_MESSAGES_COMPOSE COMPOSE
#define QSETTING_MODE_MESSAGES_COMPOSE QUOTE(SETTING_MODE_MESSAGES_COMPOSE)

#define SETTING_MODE mode
#define QSETTING_MODE QUOTE(SETTING_MODE)
#define QSETTING_MAP_SCALE_MIN QUOTE(mapScaleMin)
#define QSETTING_MAP_SCALE_MAX QUOTE(mapScaleMax)
#define QSETTING_POSITION_DIALOG QUOTE(dlgIfPosition)
#define QSETTING_POSITION_DISPLAY QUOTE(dspIfPosition)
#define QSETTING_SHOW_ICON_TEXT QUOTE(showIconText)
#define QSETTING_SHOW_MENU QUOTE(showMenu)
#define QSETTING_MAP_WORLD_POS QUOTE(mapWorldPos)
#define QSETTING_MAP_SCALE_DISPLAY QUOTE(mapScaleDsp)
#define QSETTING_MAP_SCALE_DIALOG QUOTE(mapScaleDlg)
#define QSETTING_MAP_TYPES QUOTE(mapTypes)
#define QSETTING_CURRENT_MAP_TYPE QUOTE(mapType)
#define SETTING_CAM_UAV uavCam
#define QSETTING_CAM_UAV QUOTE(SETTING_CAM_UAV)
#define SETTING_CAM_HELMET hCam
#define QSETTING_CAM_HELMET QUOTE(SETTING_CAM_HELMET)
#define QSETTING_MAP_TOOLS QUOTE(mapTools)
#define QSETTING_NIGHT_MODE QUOTE(nightMode)
#define QSETTING_BRIGHTNESS QUOTE(brightness)

#define QMAP_TYPE_SAT QUOTE(SAT)
#define QMAP_TYPE_TOPO QUOTE(TOPO)
#define QMAP_TYPE_BLACK QUOTE(BLK)

