name = "catTab"
prefix = "Ctab"
author = "Cat Harsis, Riouken & Gundy"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

[files]
include = [
    "mod.cpp",
    "settings/ctab_class_settings.hpp",
    "custom_backgrounds/*.paa",
    "custom_backgrounds/*.jpg",
    "*.paa",
]

exclude = [
    "*.png",
    "*.pdn",
]

[version]
git_hash = 0 # Disabled
